version: '2'

services:
  spark-worker-late:
    container_name: spark-worker-late
    image: spark-custom
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://192.168.0.4:7078
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_PORT=5001
      - SPARK_WORKER_WEBUI_PORT=9081
      - SPARK_PUBLIC_DNS=192.168.0.5
      - SPARK_LOCAL_HOSTNAME=192.168.0.5
    ports:
      - '5001:5001'
      - '9081:9081'
    network_mode: 'host'
