version: '2'

services:
  rabbitmq:
    container_name: rabbitmq
    image: docker.io/bitnami/rabbitmq:3.9
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=rheaAdmin
      - RABBITMQ_PASSWORD=adminRhea
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - '/home/user/deploy/rabbitmq/data:/bitnami/rabbitmq/mnesia'
