version: '2'

services:
  spark-driver-temp:
    container_name: spark-driver-temp
    image: spark-driver
    environment:
      - BROKERS=["192.168.0.3", "192.168.0.4", "192.168.0.5", "192.168.0.6"]
      - PORT=9000
      - TYPE=temp
      - BATCH_DURATION=3600
      - SPARK_MASTER=spark://192.168.0.4:7077
      - DRIVER_HOST=192.168.0.5
      - MONGO_URI=mongodb://rheaAdmin:****Rhea@192.168.0.6/rhea
    network_mode: 'host'
  spark-driver-hum:
    container_name: spark-driver-hum
    image: spark-driver
    environment:
      - BROKERS=["192.168.0.3", "192.168.0.4", "192.168.0.5", "192.168.0.6"]
      - PORT=9002
      - TYPE=hum
      - BATCH_DURATION=3600
      - SPARK_MASTER=spark://192.168.0.4:7077
      - DRIVER_HOST=192.168.0.5
      - MONGO_URI=mongodb://rheaAdmin:****Rhea@192.168.0.6/rhea
    network_mode: 'host'
