version: '2'

services:
  spark-driver-late-temp:
    container_name: spark-driver-late-temp
    image: spark-driver-late
    environment:
      - BROKERS=["192.168.0.3", "192.168.0.4", "192.168.0.5", "192.168.0.6"]
      - PORT=9001
      - TYPE=temp
      - BATCH_DURATION=3600
      - SPARK_MASTER=spark://192.168.0.4:7077
      - DRIVER_HOST=192.168.0.5
      - MONGO_URI=mongodb://rheaAdmin:adminRhea@192.168.0.6/rhea
    network_mode: 'host'
  spark-driver-late-hum:
    container_name: spark-driver-late-hum
    image: spark-driver-late
    environment:
      - BROKERS=["192.168.0.3", "192.168.0.4", "192.168.0.5", "192.168.0.6"]
      - PORT=9003
      - TYPE=hum
      - BATCH_DURATION=3600
      - SPARK_MASTER=spark://192.168.0.4:7077
      - DRIVER_HOST=192.168.0.5
      - MONGO_URI=mongodb://rheaAdmin:adminRhea@192.168.0.6/rhea
    network_mode: 'host'
